added autoconfirm to updateall

diff --git a/updateall b/updateall
--- a/updateall
+++ b/updateall
@@ -23,7 +23,7 @@ case $1 in
 
 	#undefined option
 	-*)
-		echo "updateall: Undefined option '$1'."
+		echo "updateall: Undefined option '$1'." >&2
 		exit 1
 	;;
 
@@ -31,40 +31,52 @@ case $1 in
 	*)
 
 		#1) update
-		echo -e "\nUpdating package list...\n" && sudo apt update || {
-			echo "updateall: Error updating packages list."
+		echo -e "\nUpdating package list...\n"
+		sudo apt update | yes
+		if [[ $PIPESTATUS[0] != 0 ]]; then
+			echo "updateall: Error updating packages list." >&2
 			exit 1
-		}
+		fi
 
 		#2) full-upgrade
-		echo -e "\nUpgrading packages...\n" && sudo apt full-upgrade || {
-			echo "updateall: Error upgrading packages."
+		echo -e "\nUpgrading packages...\n"
+		sudo apt full-upgrade | yes
+		if [[ $PIPESTATUS[0] != 0 ]]; then
+			echo "updateall: Error upgrading packages." >&2
 			exit 1
-		}
+		fi
 
 		#3) fix broken
-		echo -e "\nFixing broken packages...\n" && sudo apt install --fix-broken || {
-			echo "updateall: Error fixing broken packages."
+		echo -e "\nFixing broken packages...\n"
+		sudo apt install --fix-broken | yes
+		if [[ $PIPESTATUS[0] != 0 ]]; then
+			echo "updateall: Error fixing broken packages." >&2
 			exit 1
-		}
+		fi
 
 		#4) fix missing
-		echo -e "\nFixing missing packages...\n" && sudo apt install --fix-missing || {
-			echo "updateall: Error fixing missing packages."
+		echo -e "\nFixing missing packages...\n"
+		sudo apt install --fix-missing | yes
+		if [[ $PIPESTATUS[0] != 0 ]]; then
+			echo "updateall: Error fixing missing packages." >&2
 			exit 1
-		}
+		fi
 
 		#5) remove unused
-		echo -e "\nRemoving unused packages...\n" && sudo apt autoremove || {
-			echo "updateall: Error removing unused packages."
+		echo -e "\nRemoving unused packages...\n"
+		sudo apt autoremove | yes
+		if [[ $PIPESTATUS[0] != 0 ]]; then
+			echo "updateall: Error removing unused packages." >&2
 			exit 1
-		}
+		fi
 
 		#6) clean apt folders
-		echo -e "\nCleaning all...\n" && sudo apt autoclean || {
-			echo "updateall: Error cleaning apt folders."
+		echo -e "\nCleaning all...\n"
+		sudo apt autoclean | yes
+		if [[ $PIPESTATUS[0] != 0 ]]; then
+			echo "updateall: Error cleaning apt folders." >&2
 			exit 1
-		}
+		fi
 		echo -e "\nAll packages have been updated."
 	;;
 esac
